### ISSUE TITLE
API for fetching node source

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#822]
VNodes will no longer container source information, primarily because that information is only needed when _requested_ (such as making edits, or meta-selecting elements). 

There will need to be backwards compatibility with the current codebase - particularly around _edits_. E.g:

- Dragging & resizing frames
- Copying & pasting nodes

Copy + pasting is a bit trickier since that demands information to be available _synchronously_, which means that the vnode source will need to be retrieved before that happens. Only event I can think of when to retrieve that information is on click events, or better, all _selection_ events (click, tab, etc). 

General flow would be:

USER_SELECTED_CANVAS_ELEMENT -> fetchNodeSource() -> NODE_SOURCE_LOADED -> store to global state

Then:

COPY_COMMAND_EXECUTED -> copy node source

☝️ this is a good starting point. Once _this_ is in, then we can remove the diffing & patching for virtual objects. 

#### TODOs

- [ ] wire up new flow for retrieving node source
- [ ] Remove diffing & patching for vnode
- [ ] rename sourceId to $sourceId

ETA for this I _think_ is 1-2 full days max. After this is done, that will tee-up work for the new inspector.
